server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}/loki/api/v1/push

scrape_configs:
  - job_name: impact-graph-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: impact-graph-logs
          __path__: /var/giveth/logs/impact-graph/*

  - job_name: auth-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-logs
          __path__: /var/giveth/logs/auth/*

  - job_name: notification-center-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: notification-center-logs
          __path__: /var/giveth/logs/notification-center/*

  - job_name: giveconomy-notification-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: giveconomy-notification-service-logs
          __path__: /var/giveth/logs/giveconomy-notification-service/*

  - job_name: api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-logs
          __path__: /var/giveth/logs/api/*
