server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}/loki/api/v1/push

tenant_id: dev

scrape_configs:
  - job_name: dev-impact-graph-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dev-impact-graph-logs
          __path__: /var/giveth/logs/impact-graph/*

  - job_name: dev-auth-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dev-auth-logs
          __path__: /var/giveth/logs/auth/*

  - job_name: dev-notification-center-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dev-notification-center-logs
          __path__: /var/giveth/logs/notification-center/*

  - job_name: dev-giveconomy-notification-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dev-giveconomy-notification-service-logs
          __path__: /var/giveth/logs/giveconomy-notification-service/*

  - job_name: dev-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dev-api-logs
          __path__: /var/giveth/logs/api/*
